ifndef root
    include $(dir $(lastword $(MAKEFILE_LIST)))../Makefile
    $(call set_default_goal,CASVISITINGRENDERINGINFIX)
else
    $(call make_so,CASVISITINGRENDERINGINFIX,castlecasvisitingrenderinginfix)
endif
