ifndef TOPLEVELWD
    include $(dir $(lastword $(MAKEFILE_LIST)))../makefile
    $(call set_default_goal,CASVISITINGRENDERINGINFIX)
else
    $(call make_so,CASVISITINGRENDERINGINFIX,castlecasvisitingrenderinginfix)
endif
