#!/bin/bash
export LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib:/home/dsicilia/lib:$LD_LIBRARY_PATH
export PATH=.:$PATH

perftest "$@"
#gdb --args ./perftest $*
#valgrind --tool=cachegrind perftest $COUNT
